language: android
java: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
before_install:
  - openssl aes-256-cbc -K $encrypted_d17fc99482d5_key -iv $encrypted_d17fc99482d5_iv -in secrets.tar.xz.enc -out secrets.tar.xz -d
  - tar xvf secrets.tar.xz
  #- mv google-services.json app/
  - chmod +x gradlew
  - export TZ=America/Santiago
script:
  - ./gradlew clean
  - ./gradlew assembleDebug
  - ./gradlew test
